### PR TITLE
fixes Issue#20

### PR DESCRIPTION
**Pull request by tech4GT**
Signed-off-by: tech4GT <varun.gupta1798@gmail.com>

### CODE REVIEW

**Comment by championswimmer** [comment]
this has to be done as per the new directory status.

**Comment by tech4GT** [comment]
@championswimmer done!

**Comment by abhishek1208** [comment]
@championswimmer  Sir please review this so that we can start working on other dependent issues!

**Comment by championswimmer** [comment]
@abhishek1208 it has to be refactored because api files are moved

**Comment by tech4GT** [comment]
@championswimmer sir i have done it according to the new structure but please review this before accepting any other pull requests since it can cause further conflicts

**Pull request merged**
