### PR TITLE
modularized db actions

### PR DESCRIPTION
**Pull request by apoorvaagupta**
solves #13

### CODE REVIEW

**Comment by abhishek1208** [comment]
I commented on this issue and self assigned it! 
It would have saved the time of one of us if you would have read the comment!

**Comment by tech4GT** [comment]
This code won't do since some db functions of one module use other db functions from different modules and the whole thing has to be moved out of util

**Comment by apoorvaagupta** [comment]
@abhishek1208 I had completed  90% of the task when you assigned it to yourself. But as you are a collaborator in this project you can assign the issues but i can't. So when i started working on this issue i couldnt asign it to myself so that you would know.
Also, issue 12 can be solved after 13 as well.

**Comment by abhishek1208** [comment]
@apoorvaagupta 

1) I had fixed the issue #16 and #10 and was testing the whole code before you sent the PR for #10  but since I had not mentioned in the comments before so that was all fine!

2) But for the issue #13, I had mentioned in the comments that I'd be working on them
**Time stats**
You sent PR for #16 and #10 at **11:14 pm**
So just to be safe,
At **11:18 pm** I mentioned in the comments that I'd be working on #13 since all my effort had gone waste in #10 and #16  and you made a PR for this issue #13 at **12:00 am**
So AFAIK, I commented way before you could go to 90% completion!

3) You were not able to self-assign, but the commenting option in my knowledge is available to everyone! If you would have commented, I'd have happily worked on a separate issue!

4) Also, I took some time to make a pull request since testing had to be done because of the problem Varun has mentioned in the above comment since the refactoring had to be done carefully!

5) **The small point I'm trying to make is please comment or make others know before you are working on an issue so that the other person can work on a different issue otherwise the effort goes down the drain!
There are a lot of issues and we can happily work on them separately!**


Goodluck!

**Pull request closed without merging**
